[package]
name = "exifrs"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "exifrs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
kamadak-exif = "0.5.5"

